# Generated by Django 4.2.11 on 2024-04-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='option',
            field=models.CharField(choices=[('jpg', 'JPG'), ('png', 'PNG'), ('jpeg', 'JPEG')], default='JPG', max_length=6),
        ),
    ]
